name: Build Protect APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential git zlib1g-dev \
            libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev \
            libsqlite3-dev libfreetype6-dev libjpeg-dev libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev \
            libavcodec-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

          pip install --upgrade pip
          pip install buildozer kivy==2.1.0 python-telegram-bot==13.15 pyjnius pyttsx3 requests cryptography

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Protect-APK
          path: bin/*.apk
